export const BATTLE_COMBAT_TEXT = {
  en: {
    attackLabel: "Attack",
    attackHint: "Physical attack",
    defendLabel: "Defend",
    defendHint: "Raise a shield",
    healLabel: "Heal",
    promptLabel: ">_",
    promptHint: "Word-weave / spell",
    targetSuffix: "target",
    chooseEnemyHint: "Choose an enemy. This spell still strikes every enemy in range.",
    chooseSingleHint: "Self-targets always hit. Other targets use your current hit and crit chances.",
    chooseSelfHint: "This action can only affect yourself.",
    hitLabel: "hit",
    critLabel: "crit",
    cancelLabel: "cancel",
    promptPlaceholder: "attack MOR defense",
    promptHelp:
      'Word-weaves accept attack/defense with MOR, UBT, or XLEW alone as a fire rune. Other spell names still cast normally.',
    promptBusyLabel: "phrase is binding...",
    judgementLabel: "JUDGMENT",
    lexiconLabel: "LEXICON",
    decipherLabel: "Decipher",
    combinationLabel: "Combine",
    stabilityLabel: "Stability",
    strengthLabel: "STR",
    agilityLabel: "AGI",
    potionAriaLabel: "Drag the health potion onto the player",
    potionLabel: "POTION",
    potionTooltip: "heal +8 hp, free action",
    monsterTurnMessageTemplate: "{monsterName} acts beyond the torchlight...",
    shieldLabel: "Shield",
    manaLabel: "MP",
    hpLabel: "HP",
    equipmentEffectLabel: "effect:",
  },
  ko: {
    attackLabel: "공격",
    attackHint: "물리 공격",
    defendLabel: "방어",
    defendHint: "방어막 전개",
    healLabel: "회복",
    promptLabel: ">_",
    promptHint: "문장 / 주문",
    targetSuffix: "대상",
    chooseEnemyHint: "대상을 고르세요. 이 주문은 범위 안의 모든 적에게 적중합니다.",
    chooseSingleHint: "자기 자신을 고르면 반드시 맞습니다. 다른 대상은 현재 명중률과 치명타 확률을 따릅니다.",
    chooseSelfHint: "이 행동은 자신에게만 사용할 수 있습니다.",
    hitLabel: "명중",
    critLabel: "치명",
    cancelLabel: "취소",
    promptPlaceholder: "attack MOR defense",
    promptHelp:
      '공격/방어 구문에는 MOR, UBT를 쓰고, XLEW는 단독 화염 룬으로 쓸 수 있다. 그 외 주문명은 기존처럼 시전된다.',
    promptBusyLabel: "문장이 결속되는 중...",
    judgementLabel: "판정",
    lexiconLabel: "어휘력",
    decipherLabel: "해독력",
    combinationLabel: "조합력",
    stabilityLabel: "안정성",
    strengthLabel: "힘",
    agilityLabel: "민첩",
    potionAriaLabel: "체력 물약을 플레이어에게 드래그하기",
    potionLabel: "물약",
    potionTooltip: "HP +8, 무료 행동",
    monsterTurnMessageTemplate: "{monsterName}이(가) 횃불 너머에서 움직인다...",
    shieldLabel: "방어막",
    manaLabel: "MP",
    hpLabel: "HP",
    equipmentEffectLabel: "효과:",
  },
} as const;
